
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rohitraj
 */
public class search_product extends javax.swing.JFrame {

    /**
     * Creates new form search_product
     */
    public search_product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        P_cat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        P_name = new javax.swing.JTextField();
        P_id = new javax.swing.JTextField();
        P_price = new javax.swing.JTextField();
        P_quan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Product_id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(22, 58, 112, 28);

        P_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_catActionPerformed(evt);
            }
        });
        jPanel1.add(P_cat);
        P_cat.setBounds(180, 202, 93, 28);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 58, 65, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Product_category");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(22, 202, 140, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Product_name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(22, 126, 112, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Product_quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(22, 273, 140, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Product_price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(22, 352, 112, 28);

        P_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_nameActionPerformed(evt);
            }
        });
        jPanel1.add(P_name);
        P_name.setBounds(180, 126, 93, 28);

        P_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_idActionPerformed(evt);
            }
        });
        jPanel1.add(P_id);
        P_id.setBounds(180, 58, 93, 28);

        P_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_priceActionPerformed(evt);
            }
        });
        jPanel1.add(P_price);
        P_price.setBounds(180, 352, 93, 28);
        jPanel1.add(P_quan);
        P_quan.setBounds(180, 273, 93, 28);

        jLabel6.setFont(new java.awt.Font("Snap ITC", 3, 30)); // NOI18N
        jLabel6.setText("               SEARCH PRODUCT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 10, 668, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\rohitraj\\Desktop\\software-background-chimoosoft-desktop-48006.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 720, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_idActionPerformed

    private void P_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_nameActionPerformed

    private void P_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_catActionPerformed

    private void P_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            
        //String s;
        //s = getText
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
        try {
        String driver ="oracle.jdbc.driver.OracleDriver";
        Class.forName(driver);
        String JDBC_DRIVER = "jdbc:oracle:thin:@127.0.0.1:1521:XE";
        String user= "system";
        String pass="iiita123";
        con = DriverManager.getConnection(JDBC_DRIVER,user,pass);
    //    System.out.println("rohit");
        
    }catch (Exception ex) {
        JOptionPane.showMessageDialog(null,ex);
        
    }
        
           try {
             
                String user1 = P_id.getText();
                String sql = "select P_NAME , P_CATEGORY,  P_QUANTITY , P_PRICE  from PRODUCT_TABLE  where P_ID ='"+user1+"'" ;
                //System.out.println("rohit");
                st= con.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    //System.out.println("rohit");
                    //jTextarea1.setText(male.getText());
                     P_name.setText(rs.getString("P_NAME"));
                //p_id.setText(rs.getString("P_ID"));
                P_cat.setText(rs.getString("P_CATEGORY"));
                P_quan.setText(rs.getString("P_QUANTITY"));
                P_price.setText(rs.getString("P_PRICE"));
                }
                
            } 
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null,ex);
        }
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_product().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_cat;
    private javax.swing.JTextField P_id;
    private javax.swing.JTextField P_name;
    private javax.swing.JTextField P_price;
    private javax.swing.JTextField P_quan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
